package:
  name: python
  version: 0.9.1

source:
  git_rev: f7125a86a9994de100a6f96e76aed8a12d0a1dca
  git_url: https://github.com/smontanaro/python-0.9.1

requirements:
  build:
    - make

about:
  license: https://github.com/smontanaro/python-0.9.1/blob/main/README
  license_family: OTHER
  summary: Earliest known archive of Python language

