package:
  name: python
  version: 0.9.1

source:
  git_url: https://github.com/DavidMertz/python-0.9.1.git 

requirements:
  build:
    - make

about:
  license: https://github.com/DavidMertz/python-0.9.1/blob/main/README
  license_family: OTHER
  summary: Earliest known archive of Python language

